// Mock data for testing - replace with Supabase once database is set up
export const mockCategories = [
  {
    id: "cat_sarees",
    name: "Sarees",
    description: "Traditional and contemporary silk sarees",
  },
  {
    id: "cat_lehengas",
    name: "Lehengas",
    description: "Elegant lehengas for special occasions",
  },
  {
    id: "cat_blouses",
    name: "Blouses",
    description: "Designer blouses and cholis",
  },
];

export const mockProducts = [
  {
    id: "royal-kanjivaram-silk-saree",
    name: "Royal Kanjivaram Silk Saree",
    slug: "royal-kanjivaram-silk-saree",
    description:
      "Exquisite handwoven Kanjivaram saree with intricate gold zari borders and traditional temple motifs. This masterpiece showcases the finest craftsmanship of Tamil Nadu artisans, featuring pure mulberry silk and genuine gold threads. Each thread tells a story of ancient traditions and skilled craftsmanship passed down through generations.",
    price: 25999,
    images: [
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1594736797933-d0301ba5a65a?w=800&auto=format&fit=crop",
    ],
    active: true,
    in_stock: true,
    stock_count: 15,
    fabric: "Pure Kanjivaram Silk",
    color: "Deep Maroon with Gold",
    size: "One Size (6.5m with blouse piece)",
    weight: "800g",
    occasion: "Wedding, Festival",
    tags: ["premium", "handwoven", "traditional", "wedding"],
    featured: true,
    new_arrival: false,
    category_id: "cat_sarees",
    categories: { name: "Sarees" },
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "banarasi-elegance-silk-saree",
    name: "Banarasi Elegance Silk Saree",
    slug: "banarasi-elegance-silk-saree",
    description:
      "Pure Banarasi silk saree with opulent brocade work and silver zari. Woven with traditional techniques passed down through generations, this saree embodies the royal heritage of Varanasi. The intricate patterns feature classic Mughal-inspired motifs that shimmer beautifully in light.",
    price: 18999,
    images: [
      "https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1566479179817-4e8c4c4c8e2b?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1594736797933-d0301ba5a65a?w=800&auto=format&fit=crop",
    ],
    active: true,
    in_stock: true,
    stock_count: 12,
    fabric: "Pure Banarasi Silk",
    color: "Royal Blue with Silver",
    size: "One Size (6.5m with blouse piece)",
    weight: "750g",
    occasion: "Wedding, Reception",
    tags: ["banarasi", "silk", "traditional", "premium"],
    featured: true,
    new_arrival: true,
    category_id: "cat_sarees",
    categories: { name: "Sarees" },
    created_at: "2024-01-15",
    updated_at: "2024-01-15",
  },
  {
    id: "patola-heritage-saree",
    name: "Patola Heritage Saree",
    slug: "patola-heritage-saree",
    description:
      "Authentic double ikat Patola saree from Gujarat, featuring geometric patterns and vibrant colors. Each saree takes months to complete and represents the pinnacle of Indian textile artistry. This rare piece showcases the extraordinary skill of Patola weavers who create magic with silk threads.",
    price: 45999,
    images: [
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=800&auto=format&fit=crop",
    ],
    active: true,
    in_stock: true,
    stock_count: 8,
    fabric: "Pure Silk Double Ikat",
    color: "Multi-color Traditional",
    size: "One Size (6.5m with blouse piece)",
    weight: "700g",
    occasion: "Wedding, Cultural Events",
    tags: ["patola", "heritage", "handwoven", "exclusive"],
    featured: true,
    new_arrival: false,
    category_id: "cat_sarees",
    categories: { name: "Sarees" },
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
  },
  {
    id: "contemporary-silk-saree",
    name: "Contemporary Silk Saree",
    slug: "contemporary-silk-saree",
    description:
      "Modern interpretation of traditional silk saree with contemporary prints and subtle embellishments. Perfect for the modern woman who appreciates both tradition and style. Features a unique blend of classic motifs with contemporary design elements.",
    price: 12999,
    images: [
      "https://images.unsplash.com/photo-1594736797933-d0301ba5a65a?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1566479179817-4e8c4c4c8e2b?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop",
    ],
    active: true,
    in_stock: true,
    stock_count: 20,
    fabric: "Art Silk",
    color: "Dusty Rose with Gold",
    size: "One Size (6.5m with blouse piece)",
    weight: "600g",
    occasion: "Office, Party, Festival",
    tags: ["contemporary", "modern", "versatile"],
    featured: false,
    new_arrival: true,
    category_id: "cat_sarees",
    categories: { name: "Sarees" },
    created_at: "2024-01-20",
    updated_at: "2024-01-20",
  },
  {
    id: "bridal-heavy-lehenga-set",
    name: "Bridal Heavy Lehenga Set",
    slug: "bridal-heavy-lehenga-set",
    description:
      "Opulent bridal lehenga with heavy zardozi embroidery, sequins, and pearl work. Complete set includes lehenga, choli, and dupatta. A dream ensemble for your special day, crafted with the finest materials and adorned with exquisite handwork that will make you shine.",
    price: 65999,
    images: [
      "https://images.unsplash.com/photo-1571115764595-644a1f56a55c?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1594736797933-d0301ba5a65a?w=800&auto=format&fit=crop",
    ],
    active: true,
    in_stock: true,
    stock_count: 6,
    fabric: "Silk with Heavy Embroidery",
    color: "Deep Red with Gold",
    size: "Free Size (Can be customized)",
    weight: "1.2kg",
    occasion: "Wedding, Reception",
    tags: ["bridal", "heavy-work", "premium", "exclusive"],
    featured: true,
    new_arrival: true,
    category_id: "cat_lehengas",
    categories: { name: "Lehengas" },
    created_at: "2024-01-10",
    updated_at: "2024-01-10",
  },
  {
    id: "tussar-natural-saree",
    name: "Natural Tussar Silk Saree",
    slug: "tussar-natural-saree",
    description:
      "Handloom Tussar silk saree with natural texture and earthy tones. Hand-block printed with traditional motifs, this saree celebrates the beauty of natural fibers. Eco-friendly and sustainable, perfect for the conscious fashionista.",
    price: 8999,
    images: [
      "https://images.unsplash.com/photo-1566479179817-4e8c4c4c8e2b?w=800&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=800&auto=format&fit=crop",
    ],
    active: true,
    in_stock: true,
    stock_count: 25,
    fabric: "Pure Tussar Silk",
    color: "Natural Beige with Brown",
    size: "One Size (6.5m with blouse piece)",
    weight: "550g",
    occasion: "Casual, Office, Day Events",
    tags: ["tussar", "handloom", "natural", "eco-friendly"],
    featured: false,
    new_arrival: false,
    category_id: "cat_sarees",
    categories: { name: "Sarees" },
    created_at: "2024-01-05",
    updated_at: "2024-01-05",
  },
];
